steps:
  - name: 'gcr.io/cloud-builders/docker'
    aargs: ['build', '-t' , 'gcr.io/$PROJECT_ID/my-gcp', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-gcp']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-gcp',
           '--image', 'gcr.io/$PROJECT_ID/my-gcp',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']
substitutions:
  _SERVICE: 'first-try'